### ISSUE TITLE
Rename repo to `unit-conversion` or `unit-mapping`

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/units#1]
Seeing that this repo will (hopefully) become useful for models and tools beyond just energy modelling, I suggest to rename it to `unit-conversion` or `unit-mapping`

**Comment by khaeru** [comment]
‘Conversion’ and ‘mapping’ functionality are provided by pint. The intent for this repo was just to be a public, pint-compatible list of unit definitions for non-SI energy units.

**Comment by danielhuppmann** [comment]
My point is that even at this early stage, the list has currency and transport-demand mappings, which are only tangentially related to energy. Hence my suggestion to broaden the scope by broadening the repo-name (and related #2).

**Comment by danielhuppmann** [comment]
See the comment by @znicholls in [this comments](https://github.com/IAMconsortium/pyam/issues/340#issuecomment-593155357) pointing to a similar effort for [openscm](https://github.com/lewisjared/scmdata/blob/master/src/scmdata/units.py)

I'll take that as evidence for my suggestion that we need a broader repo name...

**Comment by znicholls** [comment]
Quick brainstorm from me: 'climate-units', 'iam-units', 'pyam-units', 'scm-units', 'iiasa-units'

I quite like 'iiasa-units', suggests that it's anything which is useful to IIASA analysis which ranges from currency conversions to emissions unit conversions to energy etc.

**Comment by danielhuppmann** [comment]
Just discussed this with @khaeru in the hallway, we are thinking to migrate to the `IAMconsortium` org and rename to `units` - to show that this is useful beyond IIASA and not being too specific about what kind of units it'll contain so that it can grow into whichever direction is useful.

@gidden @rgieseke @Ludee - any objections?

**Comment by gidden** [comment]
+1

**Comment by khaeru** [comment]
Resolved by (1) moving to IAMconsortium and (2) renaming to simply 'units'.
