### ISSUE TITLE
pint can't handle kilotons (kt) 

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/units#13]
pint can handle common orders of magnitude, but the term `kt` is defined as 'knot' rather than interpreted as 'kiloton'. As kt is quite common for emissions, I suggest to remove ' knot' as a unit when importing the ism-units definitions.

To replicate the error, try:
```
pint.UnitRegistry()('1000 kt').to('Mt')
```
Expected output: `1 Mt`

**Comment by khaeru** [comment]
Thoughts:
- I don't believe pint has first-class support (i.e a public function) for removing existing definitions.
  - However, by reading the pint code one could probably figure out a way to do this.
  - That code could live in this repo if it were converted to a Python package (#15), or contributed upstream to pint itself.
- Other approaches which might work but would be less desirable:
  - Maintain a variant of pint's default_en.txt, e.g. with the 'knot' line deleted.
  - Modify the contents of default_en.txt before loading it.
