### ISSUE TITLE
Package for conda-forge

### ISSUE THREAD

**Issue by khaeru** [IAMconsortium/units#22]
As noted by @danielhuppmann:

conda-forge requires that all dependencies of a package *also* be available as conda packages (conda/conda-build#548). Because pyam-iamc depends on iam-units, a conda recipe is needed for this repo.

**Comment by khaeru** [comment]
See conda-forge/staged-recipes#11824.

**Comment by danielhuppmann** [comment]
Thanks @khaeru!

**Comment by danielhuppmann** [comment]
I guess that this issue can be closed @khaeru - or why is there help wanted?

**Comment by khaeru** [comment]
@danielhuppmann I think I was just updating status for a lot of issues quickly, and did not click through to remind myself that the staged-recipe had already been accepted and the package published. Thanks for the catch!
