### ISSUE TITLE
Allow gwp-conversion between C and CO2 with metric=None

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/units#23]
This is a similar issue to #20, but refers to the conversion between C (carbon) and CO2 (carbon dioxide).

I would expect either of these two options to work:

1. Using GWP-conversion without a metric.
    ```
    iam_units.convert_gwp(None (1, 't'), 'CO2', 'C')
    ```
2. or using direct conversion in the registry.
    ```
    iam_units.registry('1 t C').to('t CO2')
    ```

**Comment by khaeru** [comment]
This seems like a good new feature to have. Currently the `metric` parameter is described as follows:
https://github.com/IAMconsortium/units/blob/5d1e20f634d1c08905d9a4e0d47ca69b8408770b/iam_units/__init__.py#L28-L30

The fix will be to change the semantics of this to:

> May be `None` if the input and output species are the same; *or* if they are both 'C', 'CO2', or synonyms.

…and then use a default value for the parameter if that condition is satisfied.
