### ISSUE TITLE
"Unknown conversion specified" in test suite with pint 0.18

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/units#31]
A new version of pint (0.18) was released last week (2021.10.26), which caused the pyam tests connected to units to fail. 
An easy and quick fix would be to pin the version of `pint <= 0.17`.
Additionally, it might be a good idea to set up nightly tests that run at least once a week so that we catch these dependency changes.

**Comment by khaeru** [comment]
Can we add some information on _how_ the tests fail, and _what_ exactly was the offending change in Pint (e.g. a link to the changelog)?

Introducing pins in setup.cfg is not totally verboten, but shouldn't be done without first considering how difficult it would be to immediately follow changes upstream. If the answer is "very difficult," then we can consider it.

**Comment by khaeru** [comment]
> Can we add some information on _how_ the tests fail, and _what_ exactly was the offending change in Pint (e.g. a link to the changelog)?

Since this is blocking #34, just opened, I will do it.

**Comment by khaeru** [comment]
The error messages (e.g. [here](https://github.com/IAMconsortium/units/runs/4153602970?check_suite_focus=true#step:5:106)) look like:
```
iam_units/__init__.py:136: in format_mass
    return format_unit(to_units_container(dict(units), registry=registry), spec)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

unit = <UnitsContainer({'kilogram CO2': 1, 'year': -1})>, spec = ':C'
registry = None, options = {}, fmt = None

    def format_unit(unit, spec, registry=None, **options):
        # registry may be None to allow formatting `UnitsContainer` objects
        # in that case, the spec may not be "Lx"
    
        if not unit:
            if spec.endswith("%"):
                return ""
            else:
                return "dimensionless"
    
        if not spec:
            spec = "D"
    
        fmt = _FORMATTERS.get(spec)
        if fmt is None:
>           raise ValueError(f"Unknown conversion specified: {spec}")
E           ValueError: Unknown conversion specified: :C

/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pint/formatting.py:408: ValueError
```
I also see in places:
```
E           ValueError: Unknown conversion specified: :~
```

**Comment by khaeru** [comment]
The changelog for pint 0.18 is [here](https://github.com/hgrecco/pint/blob/3df6536847299cff7e8390685e9c2bb4a4473366/CHANGES#L10-L42). Nothing jumps out. But someone opened hgrecco/pint#1407 2 days after this issue, so it appears to be an unanticipated breakage and possibly headed towards resolution.

**Comment by khaeru** [comment]
@phackstock if you also want to monitor for pint 0.18.1 and, once it's released, make another PR to revert #32, then we can approve and merge that PR. Otherwise, I'd prefer to wait 🙂

**Comment by phackstock** [comment]
I subscribed to the issue and set 'watch' for new releases so I should be notified if anything changes there. 
But the way I read it, is that it is intended behavior that they just didn't document well. The strategy they were discussing is rolling it back for 18.1 but including it for good in 19.0. Still that would move the problem for us.

**Comment by khaeru** [comment]
If the change is permanent, then we should adjust to it. I went ahead and looked, and it turns out that's simple. See #35.
